### ISSUE TITLE
GRPC multiplexer is being restarted every minute

### ISSUE THREAD

**Issue by 0x6c23** [blockworks-foundation/lite-rpc#323]
# Issue 

Commit https://github.com/blockworks-foundation/lite-rpc/commit/38da1ed9877cc2c1ca2e02f59d4d3d135b151ac1#diff-a9e69238f436ea544a4f20f1652a3257084e784a8733386c49c1a6a777dfa5b5L171 renamed `cleanup_without_recv_blocks` to `cleanup_without_recv_full_blocks` in `cluster-endpoints/src/grpc_multiplex.rs` (`fn create_grpc_multiplex_blocks_subscription()`), but it also removed `cleanup_without_recv_blocks = 0;` from the `processed_block_reciever`, so now every minute the multiplexer is being restarted. I don't think this is intended behavior.

# Proposed solution

Add `cleanup_without_recv_full_blocks = 0;` to the beginning of `processed_block_reciever`

**Comment by godmodegalactus** [comment]
This issue should be fixed by now.

**Comment by Estereg** [comment]
I'm still the same and I don't know how to solve it, I have everything updated absolutely everything.
2024-03-23T00:31:50.291861Z ERROR lite_rpc::rpc_tester: RPC seems down
2024-03-23T00:32:00.274130Z ERROR solana_lite_rpc_cluster_endpoints::grpc_multiplex: block or block info geyser stream stopped - restarting multiplexer (13-13-13)
2024-03-23T00:32:45.309465Z ERROR lite_rpc::rpc_tester: RPC seems down
2024-03-23T00:33:06.777954Z ERROR solana_lite_rpc_cluster_endpoints::grpc_multiplex: block or block info geyser stream stopped - restarting multiplexer (13-13-13)

**Comment by godmodegalactus** [comment]
which geyser grpc plugin are you using, we have also made a bug fix to solve grpc lagging issues.

**Comment by Pantoria** [comment]
I have the same issue. I am using yellowstone grpc
